name: all_pub_metrics
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:
  graphql:
  lints:
  test:
