name: pub_scores
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.1.0'

dependencies:
  json_annotation:
  jsontool:

dev_dependencies:
  build_runner:
  collection:
  json_serializable:
  github:
  lints:
  pool:
  pub_api_client:
    git:
      url: https://github.com/xvrh/pub_api_client.git
      ref: '099dbae'
  retry:
  test:
