name: pub_scores
description: A periodically refreshed snapshot of pub.dev and GitHub package stats.
version: 2.0.0

environment:
  sdk: '^3.8.0'

dependencies:
  json_annotation: ^4.12.0
  jsontool:

dev_dependencies:
  build_runner:
  collection:
  json_serializable:
  github:
  lints:
  pool:
  pub_api_client: ^3.2.0
  retry:
  test:
