name: 'Cron task'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  test:
    name: 'Update file'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: actions/checkout@v2
      - run: dart pub get
      - run: dart bin/cron_task.dart
