name: 'Cron task'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
jobs:
  test:
    name: 'Update file'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: actions/checkout@v4
      - run: dart pub get
      - run: dart tool/cron_task.dart
        env:
          GITHUB_DART_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash