name: 'Test'
on:
  pull_request:
jobs:
  test:
    name: 'Run tests'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - uses: actions/checkout@v4
      - run: dart pub get
      - run: dart test
